name: app_accelerometer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.1.1  # อัพเดทเป็นเวอร์ชั่นล่าสุดที่รองรับ barometer
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  # firebase_core: ^3.12.0  # ถ้าคุณต้องการเชื่อมต่อกับ Firebase
  # firebase_database: ^11.3.3  # สำหรับเก็บข้อมูลหรือส่งการแจ้งเตือน
  geolocator: ^13.0.2  # สำหรับเก็บตำแหน่ง GPS เมื่อเกิดเหตุการณ์
  http: ^1.3.0  # สำหรับส่ง API requests
  vibration: ^1.7.7  # สำหรับสั่นเตือน
  flutter_local_notifications: ^18.0.1  # สำหรับแจ้งเตือนในโหมดเบื้องหลัง
  flutter_background_service: ^5.1.0  # สำหรับทำงานในโหมดเบื้องหลัง
  # flutter_background_service_android: ^3.0.3
  # flutter_background_service_ios: ^5.0.3
  device_info_plus: ^11.3.0  # สำหรับเก็บข้อมูลอุปกรณ์
  wakelock: ^0.4.0  # ป้องกันหน้าจอล็อคเมื่อกำลังดูการแจ้งเตือนฉุกเฉิน
  # charts_flutter: ^0.12.0  # สำหรับแสดงกราฟข้อมูลจาก barometer และ accelerometer
  path_provider: ^2.1.5  # สำหรับบันทึกข้อมูลไว้ในอุปกรณ์
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  flutter_barometer: ^0.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
